// <auto-generated />
namespace proekt_internetTeh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vtoraSlika : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vtoraSlika));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071347292_vtoraSlika"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
